import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Vestido Floral de Verano',
    price: 49.99,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'summer dress',
    category: 'Vestidos',
    description: 'Un vestido ligero y aireado perfecto para los días de verano, con un estampado floral vibrante.',
    stock: 15,
  },
  {
    id: '2',
    name: 'Blusa de Seda Elegante',
    price: 39.99,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'silk blouse',
    category: 'Dama',
    description: 'Una blusa de seda sofisticada que puede vestirse para la oficina o para una salida nocturna.',
    stock: 25,
  },
  {
    id: '3',
    name: 'Bolso de Cuero',
    price: 79.99,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'leather handbag',
    category: 'Accesorios',
    description: 'Un bolso de cuero atemporal con amplio espacio para todos tus esenciales.',
    stock: 10,
  },
  {
    id: '4',
    name: 'Collar de Declaración',
    price: 25.0,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'statement necklace',
    category: 'Accesorios',
    description: 'Añade un toque de glamour a cualquier atuendo con este audaz collar de declaración.',
    stock: 30,
  },
  {
    id: '5',
    name: 'Jeans Ajustados de Tiro Alto',
    price: 59.99,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'skinny jeans',
    category: 'Dama',
    description: 'Jeans ajustados favorecedores y cómodos que se convertirán en tu prenda de referencia.',
    stock: 5,
  },
  {
    id: '6',
    name: 'Vestido de Cóctel Negro',
    price: 89.99,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'cocktail dress',
    category: 'Vestidos',
    description: 'El pequeño vestido negro perfecto para cualquier ocasión especial, con una silueta clásica.',
    stock: 12,
  },
  {
    id: '7',
    name: 'Gafas de Sol de Aviador',
    price: 19.99,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'aviator sunglasses',
    category: 'Ofertas',
    description: 'Gafas de sol de aviador clásicas para proteger tus ojos con estilo. Oferta especial.',
    stock: 50,
  },
  {
    id: '8',
    name: 'Falda Plisada Midi',
    price: 45.0,
    image: 'https://placehold.co/600x800',
    dataAiHint: 'pleated skirt',
    category: 'Dama',
    description: 'Una falda midi plisada chic y versátil que se puede combinar de muchas maneras.',
    stock: 20,
  },
];
